# Generated by Django 4.1 on 2022-12-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart_upload',
            name='id',
        ),
        migrations.AlterField(
            model_name='chart_upload',
            name='user_name',
            field=models.TextField(db_index=True, max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
